### ISSUE TITLE
Grafana 6.2.0 has problem with empty password for zabbix datasource

### ISSUE THREAD

**Issue by marcinbojko** [monitoringartist/grafana-xxl#23]
It looks like this - when using provisioning in Grafana 6.2.0, empty password for zabbix api user is being thrown as exception (unmarshal Json).
Tag of image used: 6.2
Bumping version of Grafana in Dockerfile to 6.2.5 resolves the issue.
Of course I can build my own image, but, if I may ask - are there any plans to release newer version of image?

```
    jsonData:
      addThresholds: true
      alerting: true
      alertingMinSeverity: "3"
      disableReadOnlyUsersAck: true
      username: "guest"
      password: ""
      keepCookies:
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsSkipVerify: true
      trends: true
      trendsFrom: "31d"
      trendsRange: "8d"
      zabbixVersion: "4"
```
